<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleblog"
 *
 * Auto generated by Extension Builder 2018-11-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Sample Blog',
    'description' => 'Try Blog extension.',
    'category' => 'plugin',
    'author' => 'Uros',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
